SET role oiv_admin;
SET search_path = mobiel, pg_catalog, public;

ALTER TABLE mobiel.werkvoorraad_punt ADD COLUMN bouwlaag_object varchar(50);
ALTER TABLE mobiel.werkvoorraad_lijn ADD COLUMN bouwlaag_object varchar(50);
ALTER TABLE mobiel.werkvoorraad_vlak ADD COLUMN bouwlaag_object varchar(50);

CREATE TABLE mobiel.gt_pk_metadata_table (
	table_schema varchar(32) NOT NULL,
	table_name varchar(32) NOT NULL,
	pk_column varchar(32) NOT NULL,
	pk_column_idx int4 NULL,
	pk_policy varchar(32) NULL,
	pk_sequence varchar(64) NULL,
	CONSTRAINT gt_pk_metadata_table_pk_policy_check CHECK (((pk_policy)::text = ANY (ARRAY[('sequence'::character varying)::text, ('assigned'::character varying)::text, ('autogenerated'::character varying)::text]))),
	CONSTRAINT gt_pk_metadata_table_table_schema_table_name_pk_column_key UNIQUE (table_schema, table_name, pk_column)
);

INSERT INTO mobiel.gt_pk_metadata_table (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
        VALUES ('mobiel', 'symbolen', 'id', 1, 'assigned');
INSERT INTO mobiel.gt_pk_metadata_table (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
        VALUES ('mobiel', 'lijnen', 'id', 1, 'assigned');
INSERT INTO mobiel.gt_pk_metadata_table (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
        VALUES ('mobiel', 'vlakken', 'id', 1, 'assigned');
INSERT INTO mobiel.gt_pk_metadata_table (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
        VALUES ('mobiel', 'labels', 'id', 1, 'assigned');

--LABELS
DROP TABLE IF EXISTS mobiel.label_type;
CREATE TABLE mobiel.label_type (
	gid serial PRIMARY key,
	bron_id int4,
	brontabel varchar(50),
	naam text,
	categorie text,
	symbol_name text,
	"size" int4,
	evenement bool,
	gebouw bool,
	waterongeval bool,
	bluswater bool,
	natuur bool,
	bouwlaag_object varchar(50)
);

INSERT INTO mobiel.label_type
(bron_id, brontabel, naam, categorie, symbol_name, "size", evenement, gebouw, waterongeval, bluswater, natuur, bouwlaag_object)
SELECT id, 'label', naam, 'label', symbol_name, "size", True, True, True, True, True, 'bouwlaag' FROM objecten.label_type;

INSERT INTO mobiel.label_type
(bron_id, brontabel, naam, categorie, symbol_name, "size", evenement, gebouw, waterongeval, bluswater, natuur, bouwlaag_object)
SELECT id, 'label', naam, 'label', symbol_name, size_object, True, True, True, True, True, 'object' FROM objecten.label_type;

CREATE OR REPLACE FUNCTION mobiel.complement_record_label()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    DECLARE 
    	objectid integer := NULL;
    	bouwlaagid integer := NULL;
    BEGIN 
	    IF NEW.bouwlaag_object = 'bouwlaag' THEN
	    	bouwlaagid := (SELECT b.id FROM (SELECT b.id, b.geom <-> new.geom AS dist FROM objecten.bouwlagen b WHERE b.bouwlaag = NEW.bouwlaag ORDER BY dist LIMIT 1) b);
	    	UPDATE mobiel.werkvoorraad_label SET "size" = sub."size", bouwlaag_id = bouwlaagid
			FROM
			  (
			    SELECT * FROM mobiel.label_type WHERE symbol_name = new.symbol_name AND bouwlaag_object = 'bouwlaag'
			  ) sub
			WHERE werkvoorraad_label.id = NEW.id;
	    ELSE
	    	objectid := (SELECT b.object_id FROM (SELECT b.object_id, b.geom <-> new.geom AS dist FROM objecten.terrein b ORDER BY dist LIMIT 1) b);
	    	UPDATE mobiel.werkvoorraad_label SET "size" = sub."size", object_id = objectid
			FROM
			  (
			    SELECT * FROM mobiel.label_type WHERE symbol_name = new.symbol_name AND bouwlaag_object = 'object'
			  ) sub
			WHERE werkvoorraad_label.id = NEW.id;
	    END IF;
	   RETURN NULL;
    END;
    $function$
;

CREATE OR REPLACE FUNCTION mobiel.funct_label_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN 
	    IF NEW.bron = 'oiv' THEN
			INSERT INTO mobiel.werkvoorraad_label (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, omschrijving, rotatie, size, symbol_name, bouwlaag, accepted)
  			VALUES (new.geom, new.waarden_new, 'UPDATE', new.brontabel, old.id, new.bouwlaag_id, new.omschrijving, new.rotatie, new.size, new.symbol_name, new.bouwlaag, false);
  		
			UPDATE mobiel.werkvoorraad_label
			SET geom=NEW.geom, waarden_new=NEW.waarden_new, operatie=NEW.operatie, brontabel=NEW.brontabel, bron_id=old.id, omschrijving=new.omschrijving,
				object_id=NEW.object_id, bouwlaag_id=NEW.bouwlaag_id, rotatie=NEW.rotatie, "size"=NEW.size, symbol_name=NEW.symbol_name, bouwlaag=NEW.bouwlaag
			WHERE werkvoorraad_label.id = NEW.id;
			IF NOT ST_Equals(new.geom, old.geom) THEN
                INSERT INTO mobiel.werkvoorraad_hulplijnen (geom, bron_id, brontabel, bouwlaag) 
                    VALUES (ST_MakeLine(ST_Centroid(old.geom), ST_Centroid(new.geom)), old.id, new.brontabel, new.bouwlaag);
            END IF;
	    ELSE
			UPDATE mobiel.werkvoorraad_label
			SET geom=NEW.geom, waarden_new=NEW.waarden_new, operatie=NEW.operatie, brontabel=NEW.brontabel, bron_id=old.bron_id, omschrijving=new.omschrijving, 
				object_id=NEW.object_id, bouwlaag_id=NEW.bouwlaag_id, rotatie=NEW.rotatie, "size"=NEW.size, symbol_name=NEW.symbol_name, bouwlaag=NEW.bouwlaag
			WHERE werkvoorraad_label.id = NEW.id;
			IF NOT ST_Equals(new.geom, old.geom) THEN
                INSERT INTO mobiel.werkvoorraad_hulplijnen (geom, bron_id, brontabel, bouwlaag) 
                    VALUES (ST_MakeLine(ST_Centroid(old.geom), ST_Centroid(new.geom)), old.bron_id, new.brontabel, new.bouwlaag);
            END IF;
	    END IF;
	    RETURN NULL;
    END;
$function$
;

CREATE OR REPLACE FUNCTION mobiel.funct_label_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN 
	    IF OLD.bron = 'oiv' THEN
			INSERT INTO mobiel.werkvoorraad_label (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, rotatie, size, symbol_name, bouwlaag, accepted)
  			VALUES (old.geom, old.waarden_new, 'DELETE', old.brontabel, old.id, old.bouwlaag_id, old.rotatie, old.size, old.symbol_name, old.bouwlaag, false);
  		
			UPDATE mobiel.werkvoorraad_label
			SET geom=old.geom, waarden_new=old.waarden_new, operatie=old.operatie, brontabel=old.brontabel, bron_id=old.id, 
				object_id=old.object_id, bouwlaag_id=old.bouwlaag_id, rotatie=old.rotatie, "size"=old.size, symbol_name=old.symbol_name, bouwlaag=old.bouwlaag
			WHERE werkvoorraad_label.id = old.id;
	    ELSE
			DELETE FROM mobiel.werkvoorraad_label WHERE (id = OLD.id);
	    END IF;
	    RETURN NULL;
    END;
$function$
;

DROP TABLE IF EXISTS mobiel.werkvoorraad_label;
CREATE TABLE mobiel.werkvoorraad_label (
	id serial4 NOT NULL,
	datum_aangemaakt timestamp NULL DEFAULT now(),
	datum_gewijzigd timestamp NULL,
	geom geometry(point, 28992) NULL,
	waarden_new json NULL,
	operatie varchar(10) NULL,
	brontabel varchar(50) NULL,
	bron_id int4 NULL,
	object_id int4 NULL,
	bouwlaag_id int4 NULL,
	omschrijving text,
	rotatie int4 NULL,
	"size" int4 NULL,
	symbol_name text NULL,
	accepted bool NULL,
	bouwlaag int4 NULL,
	fotografie_id int4 NULL,
	bouwlaag_object varchar(50)
	CONSTRAINT werkvoorraad_label_pkey PRIMARY KEY (id)
);
CREATE INDEX werkvoorraad_label_geom_gist ON mobiel.werkvoorraad_label USING gist (geom);

CREATE TRIGGER trg_set_insert BEFORE
INSERT
    ON
    mobiel.werkvoorraad_label FOR EACH ROW EXECUTE FUNCTION objecten.set_timestamp('datum_aangemaakt');

CREATE TRIGGER trg_set_upd BEFORE
UPDATE
    ON
    mobiel.werkvoorraad_label FOR EACH ROW EXECUTE FUNCTION objecten.set_timestamp('datum_gewijzigd');

CREATE TRIGGER trg_after_insert AFTER
INSERT
    ON
    mobiel.werkvoorraad_label FOR EACH ROW EXECUTE FUNCTION mobiel.complement_record_label();

DROP VIEW IF EXISTS mobiel.labels;
CREATE OR REPLACE VIEW mobiel.labels
AS SELECT row_number() OVER (ORDER BY sub.id) AS id,
    sub.geom,
    sub.waarden_new,
    sub.operatie,
    sub.brontabel,
    sub.bron_id,
    sub.object_id,
    sub.bouwlaag_id,
    sub.rotatie,
    sub.size,
    sub.symbol_name,
    sub.bouwlaag,
    sub.bron,
    sub.binnen_buiten
FROM ( SELECT id, geom, waarden_new, operatie, brontabel, bron_id, object_id, bouwlaag_id, omschrijving, rotatie, "size", symbol_name, bouwlaag,
    		''::text AS binnen_buiten, 'werkvoorraad'::text AS bron
	FROM mobiel.werkvoorraad_label
UNION ALL
	SELECT l.id, geom, NULL, '', 'label', l.id, 
			NULL AS object_id, bouwlaag_id, omschrijving, rotatie, lt."size", lt.symbol_name, bouwlaag,
				'bouwlaag'::text AS binnen_buiten, 'oiv'::text AS bron
	FROM objecten.bouwlaag_label l
	INNER JOIN objecten.label_type lt ON l.soort = lt.naam
UNION ALL
	SELECT l.id, geom, NULL, '', 'label', l.id,
			object_id, NULL AS bouwlaag_id, omschrijving, rotatie, lt."size", lt.symbol_name, NULL AS bouwlaag,
				'object'::text AS binnen_buiten, 'oiv'::text AS bron
	FROM objecten.object_label l
	INNER JOIN objecten.label_type lt ON l.soort = lt.naam
) sub;

CREATE TRIGGER trg_labels_upd INSTEAD OF
UPDATE
    ON
    mobiel.labels FOR EACH ROW EXECUTE FUNCTION mobiel.funct_label_update();

CREATE TRIGGER trg_labels_del INSTEAD OF
DELETE
    ON
    mobiel.labels  FOR EACH ROW EXECUTE FUNCTION mobiel.funct_label_delete();

CREATE OR REPLACE RULE labels_ins AS
    ON INSERT TO mobiel.labels DO INSTEAD  
	INSERT INTO mobiel.werkvoorraad_label (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id,
										 omschrijving, rotatie, size, symbol_name, bouwlaag, accepted, bouwlaag_object)
  VALUES (new.geom, new.waarden_new, 'INSERT'::character varying, new.brontabel, new.bron_id, new.bouwlaag_id, 
  			new.omschrijving, new.rotatie, new.size, new.symbol_name, new.bouwlaag, false, new.binnen_buiten);

CREATE OR REPLACE VIEW mobiel.categorie_labels AS 
	SELECT DISTINCT label_type.categorie, label_type.brontabel, bouwlaag_object FROM mobiel.label_type;

--SYMBOLEN
CREATE TABLE mobiel.punten_type (
	gid serial PRIMARY key,
	bron_id int4,
	brontabel varchar(50),
	naam text,
	categorie text,
	symbol_name text,
	"size" int4,
	size_object int4,
	evenement bool,
	gebouw bool,
	waterongeval bool,
	bluswater bool,
	natuur bool,
	bouwlaag_object varchar(50)
);

--INSERT SCRIPTS PUNTEN NOG TOEVOEGEN

CREATE OR REPLACE FUNCTION mobiel.complement_record_punt()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    DECLARE 
    	objectid integer := NULL;
    	bouwlaagid integer := NULL;
    BEGIN 
	    IF NEW.bouwlaag_object = 'bouwlaag' THEN
	    	bouwlaagid := (SELECT b.id FROM (SELECT b.id, b.geom <-> new.geom AS dist FROM objecten.bouwlagen b WHERE b.bouwlaag = NEW.bouwlaag ORDER BY dist LIMIT 1) b);
	    	UPDATE mobiel.werkvoorraad_punt SET "size" = sub."size", bouwlaag_id = bouwlaagid
			FROM
			  (
			    SELECT * FROM mobiel.punten_type WHERE symbol_name = new.symbol_name AND bouwlaag_object = 'bouwlaag'
			  ) sub
			WHERE werkvoorraad_punt.id = NEW.id;
	    ELSE
	    	objectid := (SELECT b.object_id FROM (SELECT b.object_id, b.geom <-> new.geom AS dist FROM objecten.terrein b ORDER BY dist LIMIT 1) b);
	    	UPDATE mobiel.werkvoorraad_punt SET "size" = sub."size", object_id = objectid
			FROM
			  (
			    SELECT * FROM mobiel.punten_type WHERE symbol_name = new.symbol_name AND bouwlaag_object = 'object'
			  ) sub
			WHERE werkvoorraad_punt.id = NEW.id;
	    END IF;
	   RETURN NULL;
    END;
    $function$
;

CREATE OR REPLACE FUNCTION mobiel.funct_symbol_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN 
	    IF NEW.bron = 'oiv' THEN
			INSERT INTO mobiel.werkvoorraad_punt (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, rotatie, size, symbol_name, bouwlaag, accepted)
  			VALUES (new.geom, new.waarden_new, 'UPDATE', new.brontabel, old.id, new.bouwlaag_id, new.rotatie, new.size, new.symbol_name, new.bouwlaag, false);
  		
			UPDATE mobiel.werkvoorraad_punt
			SET geom=NEW.geom, waarden_new=NEW.waarden_new, operatie=NEW.operatie, brontabel=NEW.brontabel, bron_id=old.id, 
				object_id=NEW.object_id, bouwlaag_id=NEW.bouwlaag_id, rotatie=NEW.rotatie, "size"=NEW.size, symbol_name=NEW.symbol_name, bouwlaag=NEW.bouwlaag
			WHERE werkvoorraad_punt.id = NEW.id;
			IF NOT ST_Equals(new.geom, old.geom) THEN
                INSERT INTO mobiel.werkvoorraad_hulplijnen (geom, bron_id, brontabel, bouwlaag) 
                    VALUES (ST_MakeLine(ST_Centroid(old.geom), ST_Centroid(new.geom)), old.id, new.brontabel, new.bouwlaag);
			END IF;
	    ELSE
			UPDATE mobiel.werkvoorraad_punt
			SET geom=NEW.geom, waarden_new=NEW.waarden_new, operatie='UPDATE', brontabel=NEW.brontabel, bron_id=old.bron_id, 
				object_id=NEW.object_id, bouwlaag_id=NEW.bouwlaag_id, rotatie=NEW.rotatie, "size"=NEW.size, symbol_name=NEW.symbol_name, bouwlaag=NEW.bouwlaag
			WHERE werkvoorraad_punt.id = NEW.id;
			IF NOT ST_Equals(new.geom, old.geom) THEN
                INSERT INTO mobiel.werkvoorraad_hulplijnen (geom, bron_id, brontabel, bouwlaag) 
                    VALUES (ST_MakeLine(ST_Centroid(old.geom), ST_Centroid(new.geom)), old.bron_id, new.brontabel, new.bouwlaag);
			END IF;
	    END IF;
	    RETURN NULL;
    END;
$function$
;

CREATE OR REPLACE FUNCTION mobiel.funct_symbol_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN 
	    IF OLD.bron = 'oiv' THEN
			INSERT INTO mobiel.werkvoorraad_punt (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, rotatie, size, symbol_name, bouwlaag, accepted)
  			VALUES (old.geom, old.waarden_new, 'DELETE', old.brontabel, old.id, old.bouwlaag_id, old.rotatie, old.size, old.symbol_name, old.bouwlaag, false);
  		
			UPDATE mobiel.werkvoorraad_punt
			SET geom=old.geom, waarden_new=old.waarden_new, operatie=old.operatie, brontabel=old.brontabel, bron_id=old.id, 
				object_id=old.object_id, bouwlaag_id=old.bouwlaag_id, rotatie=old.rotatie, "size"=old.size, symbol_name=old.symbol_name, bouwlaag=old.bouwlaag
			WHERE werkvoorraad_punt.id = old.id;
	    ELSE
			DELETE FROM mobiel.werkvoorraad_punt WHERE (id = OLD.id);
	    END IF;
	    RETURN NULL;
    END;
$function$
;

CREATE TRIGGER trg_set_insert BEFORE
INSERT
    ON
    mobiel.werkvoorraad_punt FOR EACH ROW EXECUTE FUNCTION objecten.set_timestamp('datum_aangemaakt');

CREATE TRIGGER trg_set_upd BEFORE
INSERT
    ON
    mobiel.werkvoorraad_punt FOR EACH ROW EXECUTE FUNCTION objecten.set_timestamp('datum_gewijzigd');
    
CREATE TRIGGER trg_after_insert AFTER
INSERT
    ON
    mobiel.werkvoorraad_punt FOR EACH ROW EXECUTE FUNCTION mobiel.complement_record_punt();

CREATE OR REPLACE VIEW mobiel.symbolen
AS SELECT row_number() OVER (ORDER BY sub.id) AS id,
    sub.geom,
    sub.waarden_new,
    sub.operatie,
    sub.brontabel,
    sub.bron_id,
    sub.object_id,
    sub.bouwlaag_id,
    sub.rotatie,
    sub.size,
    sub.symbol_name,
    sub.bouwlaag,
    sub.bron,
    sub.binnen_buiten
FROM ( SELECT werkvoorraad_punt.id,
    werkvoorraad_punt.geom,
    werkvoorraad_punt.waarden_new,
    werkvoorraad_punt.operatie,
    werkvoorraad_punt.brontabel,
    werkvoorraad_punt.bron_id,
    werkvoorraad_punt.object_id,
    werkvoorraad_punt.bouwlaag_id,
    werkvoorraad_punt.rotatie,
    werkvoorraad_punt.size,
    werkvoorraad_punt.symbol_name,
    werkvoorraad_punt.bouwlaag,
    ''::text AS binnen_buiten,
    'werkvoorraad'::text AS bron
   FROM mobiel.werkvoorraad_punt
UNION ALL
 SELECT bouwlaag_veiligh_install.id,
    bouwlaag_veiligh_install.geom,
    row_to_json(( SELECT d.*::record AS d
           FROM ( SELECT bouwlaag_veiligh_install.label,
                    bouwlaag_veiligh_install.bijzonderheid) d)) AS waarden_new,
    ''::character varying AS operatie,
    'veiligh_install'::character varying AS brontabel,
    bouwlaag_veiligh_install.id AS bron_id,
    NULL::integer AS object_id,
    bouwlaag_veiligh_install.bouwlaag_id,
    bouwlaag_veiligh_install.rotatie,
    bouwlaag_veiligh_install.size,
    bouwlaag_veiligh_install.symbol_name,
    bouwlaag_veiligh_install.bouwlaag,
    'bouwlaag'::text AS binnen_buiten,
    'oiv'::text AS bron
   FROM objecten.bouwlaag_veiligh_install
UNION ALL
 SELECT bouwlaag_dreiging.id,
    bouwlaag_dreiging.geom,
    row_to_json(( SELECT d.*::record AS d
           FROM ( SELECT bouwlaag_dreiging.label,
                    bouwlaag_dreiging.omschrijving) d)) AS waarden_new,
    ''::character varying AS operatie,
    'dreiging_type_id'::character varying AS brontabel,
    bouwlaag_dreiging.id AS bron_id,
    bouwlaag_dreiging.object_id,
    bouwlaag_dreiging.bouwlaag_id,
    bouwlaag_dreiging.rotatie,
    bouwlaag_dreiging.size,
    bouwlaag_dreiging.symbol_name,
    bouwlaag_dreiging.bouwlaag,
    'bouwlaag'::text AS binnen_buiten,
    'oiv'::text AS bron
   FROM objecten.bouwlaag_dreiging
) sub;

CREATE RULE symbolen_ins AS
    ON INSERT TO mobiel.symbolen DO INSTEAD  
  INSERT INTO mobiel.werkvoorraad_punt (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, rotatie, size, symbol_name, bouwlaag, accepted, bouwlaag_object)
  VALUES (new.geom, new.waarden_new, 'INSERT'::character varying, new.brontabel, new.bron_id, new.bouwlaag_id, new.rotatie, new.size, new.symbol_name, new.bouwlaag, false, new.binnen_buiten);

CREATE TRIGGER trg_symbolen_del INSTEAD OF
DELETE
    ON
    mobiel.symbolen  FOR EACH ROW EXECUTE FUNCTION mobiel.funct_symbol_delete();

CREATE TRIGGER trg_symbolen_upd INSTEAD OF
UPDATE
    ON
    mobiel.symbolen FOR EACH ROW EXECUTE FUNCTION mobiel.funct_symbol_update();

CREATE OR REPLACE VIEW mobiel.categorie_punten
AS SELECT DISTINCT punten_type.categorie, punten_type.brontabel, punten_type.bouwlaag_object FROM mobiel.punten_type;

--LIJNEN
CREATE TABLE mobiel.lijnen_type (
	gid serial PRIMARY key,
	bron_id int4 NULL,
	brontabel varchar(50) NULL,
	naam text NULL,
	categorie text NULL,
	evenement bool NULL,
	gebouw bool NULL,
	waterongeval bool NULL,
	bluswater bool NULL,
	natuur bool NULL,
	bouwlaag_object varchar(50)
);

INSERT INTO mobiel.lijnen_type (bron_id, brontabel, naam, categorie, gebouw, bouwlaag_object)
SELECT id, 'veiligh_bouwk', naam, 'algemeen', True, 'bouwlaag' FROM objecten.veiligh_bouwk_type;

INSERT INTO mobiel.lijnen_type (bron_id, brontabel, naam, categorie, evenement, gebouw, natuur, waterongeval, bouwlaag_object)
SELECT id, 'bereikbaarheid', naam, 'bereikbaarheid', True, True, True, True, 'object' FROM objecten.bereikbaarheid_type;

CREATE OR REPLACE FUNCTION mobiel.complement_record_lijn()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    DECLARE 
    	objectid integer := NULL;
    	bouwlaagid integer := NULL;
    BEGIN 
	    IF NEW.bouwlaag_object = 'bouwlaag' THEN
	    	bouwlaagid := (SELECT b.id FROM (SELECT b.id, b.geom <-> new.geom AS dist FROM objecten.bouwlagen b WHERE b.bouwlaag = NEW.bouwlaag ORDER BY dist LIMIT 1) b);
	    ELSE
	    	objectid := (SELECT b.object_id FROM (SELECT b.object_id, b.geom <-> new.geom AS dist FROM objecten.terrein b ORDER BY dist LIMIT 1) b);
	    END IF;
		UPDATE mobiel.werkvoorraad_lijn SET object_id = objectid, bouwlaag_id = bouwlaagid
		WHERE werkvoorraad_lijn.id = NEW.id;
        RETURN NEW;
    END;
    $function$
;

CREATE OR REPLACE FUNCTION mobiel.funct_lijn_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN 
	    IF NEW.bron = 'oiv' THEN
			INSERT INTO mobiel.werkvoorraad_lijn (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, symbol_name, bouwlaag, accepted)
  			VALUES (new.geom, new.waarden_new, 'UPDATE', new.brontabel, old.bron_id, new.bouwlaag_id, new.symbol_name, new.bouwlaag, false);
  		
			UPDATE mobiel.werkvoorraad_lijn
			SET geom=NEW.geom, waarden_new=NEW.waarden_new, operatie=NEW.operatie, brontabel=NEW.brontabel, bron_id=old.bron_id, 
				object_id=NEW.object_id, bouwlaag_id=NEW.bouwlaag_id, symbol_name=NEW.symbol_name, bouwlaag=NEW.bouwlaag
			WHERE werkvoorraad_lijn.id = NEW.id;
			IF NOT ST_Equals(new.geom, old.geom) THEN
                INSERT INTO mobiel.werkvoorraad_hulplijnen (geom, bron_id, brontabel, bouwlaag) 
                    VALUES (ST_MakeLine(ST_Centroid(old.geom), ST_Centroid(new.geom)), old.bron_id, new.brontabel, new.bouwlaag);
			END IF;
	    ELSE
			UPDATE mobiel.werkvoorraad_lijn
			SET geom=NEW.geom, waarden_new=NEW.waarden_new, operatie=NEW.operatie, brontabel=NEW.brontabel, bron_id=old.bron_id, 
				object_id=NEW.object_id, bouwlaag_id=NEW.bouwlaag_id, symbol_name=NEW.symbol_name, bouwlaag=NEW.bouwlaag
			WHERE werkvoorraad_lijn.id = NEW.id;
			IF NOT ST_Equals(new.geom, old.geom) THEN
                INSERT INTO mobiel.werkvoorraad_hulplijnen (geom, bron_id, brontabel, bouwlaag) 
                    VALUES (ST_MakeLine(ST_Centroid(old.geom), ST_Centroid(new.geom)), old.bron_id, new.brontabel, new.bouwlaag);
			END IF;
	    END IF;
	    RETURN NULL;
    END;
$function$
;

CREATE OR REPLACE FUNCTION mobiel.funct_lijn_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN 
	    IF OLD.bron = 'oiv' THEN
			INSERT INTO mobiel.werkvoorraad_lijn (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, symbol_name, bouwlaag, accepted)
  			VALUES (old.geom, old.waarden_new, 'DELETE', old.brontabel, old.id, old.bouwlaag_id, old.symbol_name, old.bouwlaag, false);
  		
			UPDATE mobiel.werkvoorraad_lijn
			SET geom=old.geom, waarden_new=old.waarden_new, operatie=old.operatie, brontabel=old.brontabel, bron_id=old.id, 
				object_id=old.object_id, bouwlaag_id=old.bouwlaag_id, symbol_name=old.symbol_name, bouwlaag=old.bouwlaag
			WHERE werkvoorraad_lijn.id = old.id;
	    ELSE
			DELETE FROM mobiel.werkvoorraad_lijn WHERE (id = OLD.id);
	    END IF;
	    RETURN NULL;
    END;
$function$
;

CREATE TRIGGER trg_set_insert BEFORE
INSERT
    ON
    mobiel.werkvoorraad_lijn FOR EACH ROW EXECUTE FUNCTION objecten.set_timestamp('datum_aangemaakt');

CREATE TRIGGER trg_set_upd BEFORE
INSERT
    ON
    mobiel.werkvoorraad_lijn FOR EACH ROW EXECUTE FUNCTION objecten.set_timestamp('datum_gewijzigd');
    
CREATE TRIGGER trg_after_insert AFTER
INSERT
    ON
    mobiel.werkvoorraad_lijn FOR EACH ROW EXECUTE FUNCTION mobiel.complement_record_lijn();

CREATE OR REPLACE VIEW mobiel.lijnen
AS SELECT row_number() OVER (ORDER BY sub.id) AS id,
    sub.geom,
    sub.waarden_new,
    sub.operatie,
    sub.brontabel,
    sub.bron_id,
    sub.object_id,
    sub.bouwlaag_id,
    sub.symbol_name,
    sub.bouwlaag,
    sub.bron,
    sub.binnen_buiten
   FROM ( SELECT werkvoorraad_lijn.id,
            werkvoorraad_lijn.geom,
            werkvoorraad_lijn.waarden_new,
            werkvoorraad_lijn.operatie,
            werkvoorraad_lijn.brontabel,
            werkvoorraad_lijn.bron_id,
            werkvoorraad_lijn.object_id,
            werkvoorraad_lijn.bouwlaag_id,
            werkvoorraad_lijn.symbol_name,
            werkvoorraad_lijn.bouwlaag,
            'werkvoorraad'::text AS bron,
    		''::text AS binnen_buiten
           FROM mobiel.werkvoorraad_lijn
        UNION ALL
         SELECT b.id,
            b.geom,
            row_to_json(( SELECT d.*::record AS d
                   FROM ( SELECT b.label,
                            b.obstakels,
                            b.wegafzetting) d)) AS waarden_new,
            ''::character varying AS operatie,
            'bereikbaarheid'::character varying AS brontabel,
            b.id AS bron_id,
            b.object_id,
            NULL::integer AS bouwlaag_id,
            b.soort AS symbol_name,
            NULL::integer AS bouwlaag,
            'oiv'::text AS bron,
    		'object'::text AS binnen_buiten
           FROM objecten.object_bereikbaarheid b
             JOIN objecten.bereikbaarheid_type bt ON b.soort::text = bt.naam::text
        UNION ALL
         SELECT b.id,
            b.geom,
            row_to_json(( SELECT d.*::record AS d
                   FROM ( SELECT b.label,
                            b.bijzonderheden) d)) AS waarden_new,
            ''::character varying AS operatie,
            'gebiedsgerichte_aanpak'::character varying AS brontabel,
            b.id AS bron_id,
            b.object_id,
            NULL::integer AS bouwlaag_id,
            b.soort AS symbol_name,
            NULL::integer AS bouwlaag,
            'oiv'::text AS bron,
    		'object'::text AS binnen_buiten
           FROM objecten.object_gebiedsgerichte_aanpak b
             JOIN objecten.gebiedsgerichte_aanpak_type bt ON b.soort::text = bt.naam::text
        UNION ALL
         SELECT object_isolijnen.id,
            object_isolijnen.geom,
            row_to_json(( SELECT d.*::record AS d
                   FROM ( SELECT object_isolijnen.omschrijving) d)) AS waarden_new,
            ''::character varying AS operatie,
            'isolijnen'::character varying AS brontabel,
            object_isolijnen.id AS bron_id,
            object_isolijnen.object_id,
            NULL::integer AS bouwlaag_id,
            object_isolijnen.hoogte::character varying AS symbol_name,
            NULL::integer AS bouwlaag,
            'oiv'::text AS bron,
    		'object'::text AS binnen_buiten
           FROM objecten.object_isolijnen
        UNION ALL
         SELECT b.id,
            b.geom,
            NULL::json AS waarden_new,
            ''::character varying AS operatie,
            'veiligh_bouwk'::character varying AS brontabel,
            b.id AS bron_id,
            NULL::integer AS object_id,
            b.bouwlaag_id,
            b.soort AS symbol_name,
            b.bouwlaag,
            'oiv'::text AS bron,
    		'bouwlaag'::text AS binnen_buiten
           FROM objecten.bouwlaag_veiligh_bouwk b
             JOIN objecten.veiligh_bouwk_type bt ON b.soort::text = bt.naam::text) sub;

CREATE OR REPLACE RULE lijnen_ins AS
    ON INSERT TO mobiel.lijnen DO INSTEAD  INSERT INTO mobiel.werkvoorraad_lijn (geom, waarden_new, operatie, brontabel, bron_id, object_id, bouwlaag_id, symbol_name, bouwlaag, accepted, bouwlaag_object)
  VALUES (new.geom, new.waarden_new, 'INSERT'::character varying, new.brontabel, new.bron_id, new.object_id, new.bouwlaag_id, new.symbol_name, new.bouwlaag, FALSE, NEW.binnen_buiten);

CREATE TRIGGER trg_lijnen_del INSTEAD OF
DELETE
    ON
    mobiel.lijnen FOR EACH ROW EXECUTE FUNCTION mobiel.funct_lijn_delete();

CREATE TRIGGER trg_lijnen_upd INSTEAD OF
UPDATE
    ON
    mobiel.lijnen FOR EACH ROW EXECUTE FUNCTION mobiel.funct_lijn_update();

CREATE OR REPLACE VIEW mobiel.categorie_lijnen
AS SELECT DISTINCT lijnen_type.categorie, lijnen_type.brontabel, bouwlaag_object FROM mobiel.lijnen_type;

--VLAKKEN
CREATE TABLE mobiel.vlakken_type (
	gid serial PRIMARY key,
	bron_id int4 NULL,
	brontabel varchar(50) NULL,
	naam text NULL,
	categorie text NULL,
	symbol_name text NULL,
	evenement bool NULL,
	gebouw bool NULL,
	waterongeval bool NULL,
	bluswater bool NULL,
	natuur bool NULL,
	bouwlaag_object varchar(50)
);

INSERT INTO mobiel.vlakken_type (bron_id, brontabel, naam, categorie, gebouw, bouwlaag_object)
SELECT id, 'ruimten_type', naam, 'ruimten', True, 'bouwlaag' FROM objecten.ruimten_type;

INSERT INTO mobiel.vlakken_type (bron_id, brontabel, naam, categorie, gebouw, evenement, natuur, bluswater, bouwlaag_object)
SELECT id, 'sectoren_type', naam, 'sectoren', True, True, True, True, 'object' FROM objecten.sectoren_type;

CREATE OR REPLACE FUNCTION mobiel.complement_record_vlak()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    DECLARE 
    	objectid integer := NULL;
    	bouwlaagid integer := NULL;
    BEGIN 
	    IF NEW.bouwlaag_object = 'bouwlaag' THEN
	    	bouwlaagid := (SELECT b.id FROM (SELECT b.id, b.geom <-> new.geom AS dist FROM objecten.bouwlagen b WHERE b.bouwlaag = NEW.bouwlaag ORDER BY dist LIMIT 1) b);
	    ELSE
	    	objectid := (SELECT b.object_id FROM (SELECT b.object_id, b.geom <-> new.geom AS dist FROM objecten.terrein b ORDER BY dist LIMIT 1) b);
	    END IF;
		UPDATE mobiel.werkvoorraad_vlak SET object_id = objectid, bouwlaag_id = bouwlaagid 
		WHERE werkvoorraad_vlak.id = NEW.id;
        RETURN NEW;
    END;
    $function$
;

CREATE OR REPLACE FUNCTION mobiel.funct_vlak_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN 
	    IF NEW.bron = 'oiv' THEN
			INSERT INTO mobiel.werkvoorraad_vlak (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, symbol_name, bouwlaag, accepted)
  			VALUES (new.geom, new.waarden_new, 'UPDATE', new.brontabel, old.bron_id, new.bouwlaag_id, new.symbol_name, new.bouwlaag, false);
  		
			UPDATE mobiel.werkvoorraad_vlak
			SET geom=NEW.geom, waarden_new=NEW.waarden_new, operatie=NEW.operatie, brontabel=NEW.brontabel, bron_id=old.bron_id, 
				object_id=NEW.object_id, bouwlaag_id=NEW.bouwlaag_id, symbol_name=NEW.symbol_name, bouwlaag=NEW.bouwlaag
			WHERE werkvoorraad_vlak.id = NEW.id;
			IF NOT ST_Equals(new.geom, old.geom) THEN
                INSERT INTO mobiel.werkvoorraad_hulplijnen (geom, bron_id, brontabel, bouwlaag) 
                    VALUES (ST_MakeLine(ST_Centroid(old.geom), ST_Centroid(new.geom)), old.bron_id, new.brontabel, new.bouwlaag);
			END IF;
	    ELSE
			UPDATE mobiel.werkvoorraad_vlak
			SET geom=NEW.geom, waarden_new=NEW.waarden_new, operatie=NEW.operatie, brontabel=NEW.brontabel, bron_id=old.bron_id, 
				object_id=NEW.object_id, bouwlaag_id=NEW.bouwlaag_id, symbol_name=NEW.symbol_name, bouwlaag=NEW.bouwlaag
			WHERE werkvoorraad_vlak.id = NEW.id;
			IF NOT ST_Equals(new.geom, old.geom) THEN
                INSERT INTO mobiel.werkvoorraad_hulplijnen (geom, bron_id, brontabel, bouwlaag) 
                    VALUES (ST_MakeLine(ST_Centroid(old.geom), ST_Centroid(new.geom)), old.bron_id, new.brontabel, new.bouwlaag);
			END IF;
	    END IF;
	    RETURN NULL;
    END;
$function$
;

CREATE OR REPLACE FUNCTION mobiel.funct_vlak_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN 
	    IF OLD.bron = 'oiv' THEN
			INSERT INTO mobiel.werkvoorraad_vlak (geom, waarden_new, operatie, brontabel, bron_id, bouwlaag_id, symbol_name, bouwlaag, accepted)
  			VALUES (old.geom, old.waarden_new, 'DELETE', old.brontabel, old.id, old.bouwlaag_id, old.symbol_name, old.bouwlaag, false);
  		
			UPDATE mobiel.werkvoorraad_vlak
			SET geom=old.geom, waarden_new=old.waarden_new, operatie=old.operatie, brontabel=old.brontabel, bron_id=old.id, 
				object_id=old.object_id, bouwlaag_id=old.bouwlaag_id, symbol_name=old.symbol_name, bouwlaag=old.bouwlaag
			WHERE werkvoorraad_vlak.id = old.id;
	    ELSE
			DELETE FROM mobiel.werkvoorraad_vlak WHERE (id = OLD.id);
	    END IF;
	    RETURN NULL;
    END;
$function$
;

CREATE TRIGGER trg_set_insert BEFORE
INSERT
    ON
    mobiel.werkvoorraad_vlak FOR EACH ROW EXECUTE FUNCTION objecten.set_timestamp('datum_aangemaakt');

CREATE TRIGGER trg_set_upd BEFORE
INSERT
    ON
    mobiel.werkvoorraad_vlak FOR EACH ROW EXECUTE FUNCTION objecten.set_timestamp('datum_gewijzigd');
    
CREATE TRIGGER trg_after_insert AFTER
INSERT
    ON
    mobiel.werkvoorraad_vlak FOR EACH ROW EXECUTE FUNCTION mobiel.complement_record_vlak();

CREATE OR REPLACE VIEW mobiel.lijnen
AS SELECT row_number() OVER (ORDER BY sub.id) AS id,
    sub.geom,
    sub.waarden_new,
    sub.operatie,
    sub.brontabel,
    sub.bron_id,
    sub.object_id,
    sub.bouwlaag_id,
    sub.symbol_name,
    sub.bouwlaag,
    sub.bron
   FROM ( 
	SELECT id, geom, waarden_new, operatie, brontabel, bron_id, object_id, bouwlaag_id, symbol_name, bouwlaag,
    'werkvoorraad'::text AS bron
	FROM mobiel.werkvoorraad_vlak
UNION ALL
	SELECT b.id, geom, row_to_json((SELECT d FROM (SELECT omschrijving) d)) AS waarden_new, '', 'sectoren', b.id, object_id, NULL AS bouwlaag_id, soort, NULL AS bouwlaag,
    'oiv'::text AS bron
	FROM objecten.object_sectoren b
	INNER JOIN objecten.sectoren_type bt ON b.soort = bt.naam
UNION ALL
	SELECT b.id, geom, row_to_json((SELECT d FROM (SELECT omschrijving) d)) AS waarden_new, '', 'ruimten', b.id, NULL AS object_id, bouwlaag_id, ruimten_type_id, bouwlaag,
    'oiv'::text AS bron
	FROM objecten.bouwlaag_ruimten b
	INNER JOIN objecten.ruimten_type bt ON b.ruimten_type_id = bt.naam
   ) sub;

CREATE OR REPLACE RULE vlakken_ins AS ON INSERT TO mobiel.vlakken
	DO INSTEAD
       INSERT INTO mobiel.werkvoorraad_vlak (geom, waarden_new, operatie, brontabel, bron_id, object_id, bouwlaag_id, 
	   				symbol_name, bouwlaag, accepted, bouwlaag_object)
       VALUES (new.geom, NEW.waarden_new, 'INSERT', new.brontabel, new.bron_id, NEW.object_id, new.bouwlaag_id, 
	   				new.symbol_name, new.bouwlaag, false, new.binnen_buiten);

CREATE TRIGGER trg_vlakken_del INSTEAD OF
DELETE
    ON
    mobiel.vlakken  FOR EACH ROW EXECUTE FUNCTION mobiel.funct_vlak_delete();

CREATE TRIGGER trg_vlakken_upd INSTEAD OF
UPDATE
    ON
    mobiel.vlakken FOR EACH ROW EXECUTE FUNCTION mobiel.funct_vlak_update();

CREATE OR REPLACE VIEW mobiel.categorie_vlakken
AS SELECT DISTINCT vlakken_type.categorie, vlakken_type.brontabel, bouwlaag_object FROM mobiel.vlakken_type;

-- Update versie van de applicatie
UPDATE algemeen.applicatie SET sub = 4;
UPDATE algemeen.applicatie SET revisie = 3;
UPDATE algemeen.applicatie SET db_versie = 343; -- db versie == versie_sub_revisie
UPDATE algemeen.applicatie SET datum = now();
