SET ROLE oiv_admin;

ALTER SCHEMA mobiel RENAME TO mobiel_old;

CREATE SCHEMA mobiel;

COMMENT ON SCHEMA mobiel IS 'Mobiele OIV dataset voor Mergin';

CREATE SEQUENCE mobiel.annotaties_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.bedrijfshulpverlening_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.contactpersoon_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.gebruiksfunctie_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.labels_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.lijnen_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.symbolen_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.vlakken_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE mobiel.annotaties (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(point, 28992) NULL,
	tekst text NOT NULL,
	plaatsing int4 DEFAULT 0 NULL,
	modified_at timestamp NULL,
	modified_by text NULL,
	bouwlaag int4 NULL,
	bouwlaag_object varchar(25) NULL,
	CONSTRAINT annotaties_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.bedrijfshulpverlening (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	bron_id int4 NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	dagen text NULL,
	tijdvakbegin timestamp NULL,
	tijdvakeind timestamp NULL,
	telefoonnummer varchar(11) NULL,
	ademluchtdragend bool NULL,
	object_id int4 NOT NULL,
	modified_at timestamp NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	CONSTRAINT bedrijfshulpverlening_pkey PRIMARY KEY (id)
);
CREATE INDEX bedrijfshulpverlening_bron_id_idx ON mobiel.bedrijfshulpverlening USING btree (bron_id);
CREATE INDEX bedrijfshulpverlening_object_id_idx ON mobiel.bedrijfshulpverlening USING btree (object_id);

CREATE TABLE mobiel.bodemgesteldheid_type (
	id int2 NOT NULL,
	naam text NULL,
	omschrijving text NULL,
	CONSTRAINT bodemgesteldheid_type_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.bouwlagen (
	id int4 NOT NULL,
	geom public.geometry(multipolygon, 28992) NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	bouwlaag int4 NOT NULL,
	bouwdeel varchar(25) NULL,
	pand_id varchar(40) NULL,
	fotografie_id int4 NULL,
	CONSTRAINT bouwlagen_pkey PRIMARY KEY (id)
);
CREATE INDEX bouwlagen_bouwlaag_idx ON mobiel.bouwlagen USING btree (bouwlaag);
CREATE INDEX bouwlagen_geom_gist ON mobiel.bouwlagen USING gist (geom);

CREATE TABLE mobiel.categorie_labels (
	id int4 NOT NULL,
	categorie text NOT NULL,
	brontabel text NOT NULL,
	bouwlaag_object text NULL,
	CONSTRAINT categorie_labels_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.categorie_lijnen (
	id int4 NOT NULL,
	categorie text NOT NULL,
	brontabel text NOT NULL,
	bouwlaag_object text NULL,
	CONSTRAINT categorie_lijnen_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.categorie_symbols (
	id int4 NOT NULL,
	categorie text NOT NULL,
	brontabel text NOT NULL,
	bouwlaag_object text NULL,
	CONSTRAINT categorie_symbols_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.categorie_vlakken (
	id int4 NOT NULL,
	categorie text NOT NULL,
	brontabel text NOT NULL,
	bouwlaag_object text NULL,
	CONSTRAINT categorie_vlakken_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.contactpersoon (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	bron_id int4 NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	soort varchar(50) NULL,
	dagen text NULL,
	tijdvakbegin timestamp NULL,
	tijdvakeind timestamp NULL,
	telefoonnummer varchar(100) NULL,
	object_id int4 NOT NULL,
	modified_at timestamp NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	CONSTRAINT contactpersoon_pkey PRIMARY KEY (id)
);
CREATE INDEX contactpersoon_bron_id_idx ON mobiel.contactpersoon USING btree (bron_id);
CREATE INDEX contactpersoon_object_id_idx ON mobiel.contactpersoon USING btree (object_id);

CREATE TABLE mobiel.contactpersoon_type (
	id int2 NOT NULL,
	naam varchar(50) NULL,
	CONSTRAINT contactpersoon_type_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.gebruiksfunctie (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	bron_id int4 NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	soort text NULL,
	object_id int4 NOT NULL,
	modified_at timestamp NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	CONSTRAINT gebruiksfunctie_pkey PRIMARY KEY (id)
);
CREATE INDEX gebruiksfunctie_bron_id_idx ON mobiel.gebruiksfunctie USING btree (bron_id);
CREATE INDEX gebruiksfunctie_object_id_idx ON mobiel.gebruiksfunctie USING btree (object_id);

CREATE TABLE mobiel.gebruiksfunctie_type (
	id int2 NOT NULL,
	naam text NULL,
	omschrijving text NULL,
	CONSTRAINT gebruiksfunctie_type_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.label_types (
	id int4 NOT NULL,
	naam text NOT NULL,
	symbol_name text NULL,
	size_klein numeric NULL,
	size_middel numeric NULL,
	size_groot numeric NULL,
	categorie text NOT NULL,
	bouwlaag_object text NOT NULL,
	brontabel text NOT NULL,
	CONSTRAINT label_types_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.labels (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(point, 28992) NULL,
	brontabel text NOT NULL,
	bron_id int8 NULL,
	object_id int8 NULL,
	bouwlaag_id int8 NULL,
	omschrijving text NULL,
	rotatie numeric NULL,
	"size" numeric NULL,
	symbol_name text NULL,
	bouwlaag int4 NULL,
	bouwlaag_object text NULL,
	bron text DEFAULT 'oiv'::text NULL,
	formaat text NULL,
	oiv_datum_aangemaakt timestamp NULL,
	oiv_datum_gewijzigd timestamp NULL,
	opmerking text NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	modified_at timestamp NULL,
	modified_by text NULL,
	CONSTRAINT labels_pkey PRIMARY KEY (id)
);
CREATE INDEX labels_bouwlaag_id_idx ON mobiel.labels USING btree (bouwlaag_id);
CREATE INDEX labels_bron_id_idx ON mobiel.labels USING btree (bron_id);
CREATE INDEX labels_object_id_idx ON mobiel.labels USING btree (object_id);
CREATE INDEX labels_sync_status_idx ON mobiel.labels USING btree (sync_status);

CREATE TRIGGER trg_werkvoorraad_label_ins BEFORE
INSERT
    ON
    mobiel.labels FOR EACH ROW EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_label_ins();
CREATE TRIGGER trg_werkvoorraad_label_upd BEFORE
UPDATE
    ON
    mobiel.labels FOR EACH ROW
    WHEN ((old.* IS DISTINCT
FROM
    new.*)) EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_label_upd();
CREATE TRIGGER trg_werkvoorraad_label_del BEFORE
DELETE
    ON
    mobiel.labels FOR EACH ROW EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_label_del();

CREATE TABLE mobiel.lijn_types (
	id int4 NOT NULL,
	naam text NOT NULL,
	categorie text NOT NULL,
	bouwlaag_object text NOT NULL,
	brontabel text NOT NULL,
	CONSTRAINT lijn_types_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.lijnen (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(multilinestring, 28992) NULL,
	brontabel text NOT NULL,
	bron_id int8 NULL,
	object_id int8 NULL,
	bouwlaag_id int8 NULL,
	symbol_name text NULL,
	bouwlaag int4 NULL,
	bouwlaag_object text NULL,
	bron text DEFAULT 'oiv'::text NULL,
	oiv_datum_aangemaakt timestamp NULL,
	oiv_datum_gewijzigd timestamp NULL,
	opmerking text NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	modified_at timestamp NULL,
	modified_by text NULL,
	CONSTRAINT lijnen_pkey PRIMARY KEY (id)
);
CREATE INDEX lijnen_bouwlaag_id_idx ON mobiel.lijnen USING btree (bouwlaag_id);
CREATE INDEX lijnen_bron_id_idx ON mobiel.lijnen USING btree (bron_id);
CREATE INDEX lijnen_object_id_idx ON mobiel.lijnen USING btree (object_id);
CREATE INDEX lijnen_sync_status_idx ON mobiel.lijnen USING btree (sync_status);

CREATE TRIGGER trg_werkvoorraad_lijn_ins BEFORE
INSERT
    ON
    mobiel.lijnen FOR EACH ROW EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_lijn_ins();
CREATE TRIGGER trg_werkvoorraad_lijn_upd BEFORE
UPDATE
    ON
    mobiel.lijnen FOR EACH ROW
    WHEN ((old.* IS DISTINCT
FROM
    new.*)) EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_lijn_upd();
CREATE TRIGGER trg_werkvoorraad_lijn_del BEFORE
DELETE
    ON
    mobiel.lijnen FOR EACH ROW EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_lijn_del();

CREATE TABLE mobiel.object_type (
	id int2 NOT NULL,
	naam varchar(100) NULL,
	symbol_name text NULL,
	"size" int4 NULL,
	symbol_type text DEFAULT 'c'::algemeen.symb_type NULL,
	actief_ruimtelijk bool DEFAULT true NULL,
	symbol_svg_png varchar(5) NULL,
	CONSTRAINT object_type_naam_key UNIQUE (naam),
	CONSTRAINT object_type_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.objecten (
	id int4 NOT NULL,
	geom public.geometry(point, 28992) NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	basisreg_identifier varchar(254) NULL,
	formelenaam varchar(255) NULL,
	bijzonderheden text NULL,
	pers_max int4 NULL,
	pers_nietz_max int4 NULL,
	datum_geldig_tot timestamp NULL,
	datum_geldig_vanaf timestamp NULL,
	bron varchar(3) NULL,
	bron_tabel varchar(25) NULL,
	fotografie_id int4 NULL,
	bodemgesteldheid_type_id int4 NULL,
	min_bouwlaag int4 NULL,
	max_bouwlaag int4 NULL,
	typeobject text NULL,
	"share" bool NULL,
	symbol_name text NULL,
	"size" int4 NULL,
	CONSTRAINT objecten_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.styles (
	id int4 NOT NULL,
	laagnaam varchar(100) NULL,
	soortnaam varchar(100) NULL,
	lijndikte numeric(5, 2) NULL,
	lijnkleur varchar(9) NULL,
	lijnstijl text NULL,
	vulkleur varchar(9) NULL,
	vulstijl text NULL,
	verbindingsstijl text NULL,
	eindstijl text NULL,
	CONSTRAINT styles_pkey PRIMARY KEY (id),
	CONSTRAINT styles_soortnaam_key UNIQUE (soortnaam)
);

CREATE TABLE mobiel.symbol_types (
	id int4 NOT NULL,
	naam text NOT NULL,
	symbol_name text NULL,
	size_klein numeric NULL,
	size_middel numeric NULL,
	size_groot numeric NULL,
	symbol_type text NULL,
	anchorpoint text NULL,
	categorie text NOT NULL,
	bouwlaag_object text NOT NULL,
	brontabel text NOT NULL,
	symbol_svg_png text NULL,
	CONSTRAINT symbol_types_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.symbolen (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	orig_id int8 NULL,
	geom public.geometry(point, 28992) NULL,
	brontabel text NOT NULL,
	bron_id int8 NULL,
	object_id int8 NULL,
	bouwlaag_id int8 NULL,
	symbol_name text NULL,
	rotatie numeric NULL,
	"size" numeric NULL,
	bouwlaag int4 NULL,
	bouwlaag_object text NULL,
	bron text DEFAULT 'oiv'::text NULL,
	oiv_datum_aangemaakt timestamp NULL,
	oiv_datum_gewijzigd timestamp NULL,
	opmerking text NULL,
	formaat text NULL,
	"label" text NULL,
	label_positie text NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	modified_at timestamp NULL,
	modified_by text NULL,
	CONSTRAINT symbolen_pkey PRIMARY KEY (id)
);
CREATE INDEX symbolen_bouwlaag_id_idx ON mobiel.symbolen USING btree (bouwlaag_id);
CREATE INDEX symbolen_bron_id_idx ON mobiel.symbolen USING btree (bron_id);
CREATE INDEX symbolen_object_id_idx ON mobiel.symbolen USING btree (object_id);
CREATE INDEX symbolen_sync_status_idx ON mobiel.symbolen USING btree (sync_status);

CREATE TRIGGER trg_werkvoorraad_symbool_ins BEFORE
INSERT
    ON
    mobiel.symbolen FOR EACH ROW EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_symbool_ins();
CREATE TRIGGER trg_werkvoorraad_symbool_upd BEFORE
UPDATE
    ON
    mobiel.symbolen FOR EACH ROW
    WHEN ((old.* IS DISTINCT
FROM
    new.*)) EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_symbool_upd();
CREATE TRIGGER trg_werkvoorraad_symbool_del BEFORE
DELETE
    ON
    mobiel.symbolen FOR EACH ROW EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_symbool_del();

CREATE TABLE mobiel.vlak_types (
	id int4 NOT NULL,
	naam text NOT NULL,
	categorie text NOT NULL,
	bouwlaag_object text NOT NULL,
	brontabel text NOT NULL,
	CONSTRAINT vlak_types_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.vlakken (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(multipolygon, 28992) NULL,
	brontabel text NOT NULL,
	bron_id int8 NULL,
	object_id int8 NULL,
	bouwlaag_id int8 NULL,
	symbol_name text NULL,
	bouwlaag int4 NULL,
	bouwlaag_object text NULL,
	bron text DEFAULT 'oiv'::text NULL,
	oiv_datum_aangemaakt timestamp NULL,
	oiv_datum_gewijzigd timestamp NULL,
	opmerking text NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	modified_at timestamp NULL,
	modified_by text NULL,
	CONSTRAINT vlakken_pkey PRIMARY KEY (id)
);
CREATE INDEX vlakken_bouwlaag_id_idx ON mobiel.vlakken USING btree (bouwlaag_id);
CREATE INDEX vlakken_bron_id_idx ON mobiel.vlakken USING btree (bron_id);
CREATE INDEX vlakken_object_id_idx ON mobiel.vlakken USING btree (object_id);
CREATE INDEX vlakken_sync_status_idx ON mobiel.vlakken USING btree (sync_status);

CREATE TRIGGER trg_werkvoorraad_vlak_ins BEFORE
INSERT
    ON
    mobiel.vlakken FOR EACH ROW EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_vlak_ins();
CREATE TRIGGER trg_werkvoorraad_vlak_upd BEFORE
UPDATE
    ON
    mobiel.vlakken FOR EACH ROW
    WHEN ((old.* IS DISTINCT
FROM
    new.*)) EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_vlak_upd();
CREATE TRIGGER trg_werkvoorraad_vlak_del BEFORE
DELETE
    ON
    mobiel.vlakken FOR EACH ROW EXECUTE FUNCTION mobiel_sync.func_werkvoorraad_vlak_del();

-- Update versie van de applicatie
UPDATE algemeen.applicatie SET sub = 7;
UPDATE algemeen.applicatie SET revisie = 4;
UPDATE algemeen.applicatie SET db_versie = 3704; -- db versie == versie_sub_revisie
UPDATE algemeen.applicatie SET omschrijving = '';
UPDATE algemeen.applicatie SET datum = now();