SET ROLE oiv_admin;

ALTER SCHEMA mobiel RENAME TO mobiel_old;

CREATE SCHEMA mobiel;

COMMENT ON SCHEMA mobiel IS 'Mobiele OIV dataset voor Mergin';

CREATE SEQUENCE mobiel.annotaties_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.bedrijfshulpverlening_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.contactpersoon_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.gebruiksfunctie_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.labels_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.lijnen_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.symbolen_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE SEQUENCE mobiel.vlakken_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE mobiel.annotaties (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(point, 28992) NULL,
	tekst text NOT NULL,
	plaatsing int4 DEFAULT 0 NULL,
	modified_at timestamp NULL,
	modified_by text NULL,
	bouwlaag int4 NULL,
	bouwlaag_object varchar(25) NULL,
	CONSTRAINT annotaties_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.bedrijfshulpverlening (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	bron_id int4 NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	dagen text NULL,
	tijdvakbegin timestamp NULL,
	tijdvakeind timestamp NULL,
	telefoonnummer varchar(11) NULL,
	ademluchtdragend bool NULL,
	object_id int4 NOT NULL,
	modified_at timestamp NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	CONSTRAINT bedrijfshulpverlening_pkey PRIMARY KEY (id)
);
CREATE INDEX bedrijfshulpverlening_bron_id_idx ON mobiel.bedrijfshulpverlening USING btree (bron_id);
CREATE INDEX bedrijfshulpverlening_object_id_idx ON mobiel.bedrijfshulpverlening USING btree (object_id);

CREATE TABLE mobiel.bodemgesteldheid_type (
	id int2 NOT NULL,
	naam text NULL,
	omschrijving text NULL,
	CONSTRAINT bodemgesteldheid_type_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.bouwlagen (
	id int4 NOT NULL,
	geom public.geometry(multipolygon, 28992) NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	bouwlaag int4 NOT NULL,
	bouwdeel varchar(25) NULL,
	pand_id varchar(40) NULL,
	fotografie_id int4 NULL,
	CONSTRAINT bouwlagen_pkey PRIMARY KEY (id)
);
CREATE INDEX bouwlagen_bouwlaag_idx ON mobiel.bouwlagen USING btree (bouwlaag);
CREATE INDEX bouwlagen_geom_gist ON mobiel.bouwlagen USING gist (geom);

CREATE TABLE mobiel.categorie_labels (
	id int4 NOT NULL,
	categorie text NOT NULL,
	brontabel text NOT NULL,
	bouwlaag_object text NULL,
	CONSTRAINT categorie_labels_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.categorie_lijnen (
	id int4 NOT NULL,
	categorie text NOT NULL,
	brontabel text NOT NULL,
	bouwlaag_object text NULL,
	CONSTRAINT categorie_lijnen_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.categorie_symbols (
	id int4 NOT NULL,
	categorie text NOT NULL,
	brontabel text NOT NULL,
	bouwlaag_object text NULL,
	CONSTRAINT categorie_symbols_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.categorie_vlakken (
	id int4 NOT NULL,
	categorie text NOT NULL,
	brontabel text NOT NULL,
	bouwlaag_object text NULL,
	CONSTRAINT categorie_vlakken_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.contactpersoon (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	bron_id int4 NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	soort varchar(50) NULL,
	dagen text NULL,
	tijdvakbegin timestamp NULL,
	tijdvakeind timestamp NULL,
	telefoonnummer varchar(100) NULL,
	object_id int4 NOT NULL,
	modified_at timestamp NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	CONSTRAINT contactpersoon_pkey PRIMARY KEY (id)
);
CREATE INDEX contactpersoon_bron_id_idx ON mobiel.contactpersoon USING btree (bron_id);
CREATE INDEX contactpersoon_object_id_idx ON mobiel.contactpersoon USING btree (object_id);

CREATE TABLE mobiel.contactpersoon_type (
	id int2 NOT NULL,
	naam varchar(50) NULL,
	CONSTRAINT contactpersoon_type_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.gebruiksfunctie (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	bron_id int4 NULL,
	datum_aangemaakt timestamp NULL,
	datum_gewijzigd timestamp NULL,
	soort text NULL,
	object_id int4 NOT NULL,
	modified_at timestamp NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	CONSTRAINT gebruiksfunctie_pkey PRIMARY KEY (id)
);
CREATE INDEX gebruiksfunctie_bron_id_idx ON mobiel.gebruiksfunctie USING btree (bron_id);
CREATE INDEX gebruiksfunctie_object_id_idx ON mobiel.gebruiksfunctie USING btree (object_id);

CREATE TABLE mobiel.gebruiksfunctie_type (
	id int2 NOT NULL,
	naam text NULL,
	omschrijving text NULL,
	CONSTRAINT gebruiksfunctie_type_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.label_types (
	id int4 NOT NULL,
	naam text NOT NULL,
	symbol_name text NULL,
	size_klein numeric NULL,
	size_middel numeric NULL,
	size_groot numeric NULL,
	categorie text NOT NULL,
	bouwlaag_object text NOT NULL,
	brontabel text NOT NULL,
	CONSTRAINT label_types_pkey PRIMARY KEY (id)
);

CREATE TABLE mobiel.labels (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(point, 28992) NULL,
	brontabel text NOT NULL,
	bron_id int8 NULL,
	object_id int8 NULL,
	bouwlaag_id int8 NULL,
	omschrijving text NULL,
	rotatie numeric NULL,
	"size" numeric NULL,
	symbol_name text NULL,
	bouwlaag int4 NULL,
	bouwlaag_object text NULL,
	bron text DEFAULT 'oiv'::text NULL,
	formaat text NULL,
	oiv_datum_aangemaakt timestamp NULL,
	oiv_datum_gewijzigd timestamp NULL,
	opmerking text NULL,
	sync_status int2 DEFAULT 0 NOT NULL,
	modified_at timestamp NULL,
	modified_by text NULL,
	CONSTRAINT labels_pkey PRIMARY KEY (id)
);
CREATE INDEX labels_bouwlaag_id_idx ON mobiel.labels USING btree (bouwlaag_id);
CREATE INDEX labels_bron_id_idx ON mobiel.labels USING btree (bron_id);
CREATE INDEX labels_object_id_idx ON mobiel.labels USING btree (object_id);
CREATE INDEX labels_sync_status_idx ON mobiel.labels USING btree (sync_status);

-- Update versie van de applicatie
UPDATE algemeen.applicatie SET sub = 7;
UPDATE algemeen.applicatie SET revisie = 4;
UPDATE algemeen.applicatie SET db_versie = 3704; -- db versie == versie_sub_revisie
UPDATE algemeen.applicatie SET omschrijving = '';
UPDATE algemeen.applicatie SET datum = now();